jobs:
  test:
    name: Main
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Pull Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./test/action

name: Action

on:
  schedule:
    - cron: "25 1/3 * * *"
